name: todoapp

on:
  push:
    # Trigger this workflow only on commits pushed to the main branch
    branches:
      - master

env:
  APP_NAME: todoapp-dagger-europa

jobs:
  dagger:
    runs-on: ubuntu-latest

    env:
      # DAGGER_CACHE_FROM: type=gha,scope=dagger-cache-example-${{github.event.number}}
      # DAGGER_CACHE_TO: type=gha,mode=max,scope=dagger-cache-example-${{github.event.number}}
      DAGGER_CACHE_TO: type=local,mode=max,dest=/tmp/storage
      # DAGGER_CACHE_FROM: type=local,src=/tmp/storage
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/storage
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      # You need to run `dagger project init` locally before and commit the cue.mod directory to the repository with its contents
      - name: Deploy
        uses: dagger/dagger-for-github@v3
        env:
          DAGGER_LOG_LEVEL: "debug"
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          version: 0.2
          # To pin external dependencies, you can use `project update github.com/[package-source]@v[n]`
          cmds: |
            project update
            do load

      - name: Print Buildkitd Logs
        if: ${{ failure() }}
        run: |
          docker logs dagger-buildkitd

      - name: run
        run: docker run app-image