name: build dagger-rust

on:
  push:
    # Trigger this workflow only on commits pushed to the main branch
    branches:
      - master
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Sets env vars on push to main
        run: |
          echo "DAGGER_CACHE_TO=type=gha,mode=max,scope=dagger-rust-master" >> $GITHUB_ENV
          echo "DAGGER_CACHE_FROM=type=gha,scope=dagger-rust-master" >> $GITHUB_ENV
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Sets env vars on pull request
        run: |
          echo "DAGGER_CACHE_TO=type=gha,mode=max,scope=dagger-rust-${{github.event.number}}" >> $GITHUB_ENV
          echo "DAGGER_CACHE_FROM=type=gha,scope=dagger-rust-master type=gha,scope=dagger-rust-${{github.event.number}}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'pull_request' }}

      # You need to run `dagger project init` locally before and commit the cue.mod directory to the repository with its contents
      - name: Test
        uses: dagger/dagger-for-github@v3
        env:
          DAGGER_LOG_LEVEL: "debug"
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          version: 0.2
          cmds: |
            do test

      - name: Print Buildkitd Logs
        if: ${{ failure() }}
        run: |
          docker logs dagger-buildkitd

      - name: run
        run: docker run app-image